# Generated by Django 3.0.5 on 2020-05-31 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_avatar_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={'get_latest_by': 'created_at', 'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username', 'email']},
        ),
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='secret_email_token',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='verification_email_sent_at',
            field=models.DateTimeField(null=True),
        ),
    ]
