# Generated by Django 3.0.5 on 2020-06-06 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='discount',
        ),
    ]
