# Generated by Django 3.0.5 on 2020-06-05 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='price_per_item',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='total_price',
            field=models.FloatField(default=0),
        ),
    ]
