# Generated by Django 3.0.5 on 2020-06-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(default='', upload_to='img'),
            preserve_default=False,
        ),
    ]
