# Generated by Django 3.0.5 on 2020-06-02 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200531_2319'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
