# Generated by Django 3.0.5 on 2020-06-02 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_delete_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Product',
            name='stock',
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
