# Generated by Django 3.0.5 on 2020-06-02 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200602_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cat',
            new_name='category',
        ),
    ]
