# Generated by Django 3.0.5 on 2020-06-02 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20200602_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.CharField(max_length=200),
        ),
    ]
